export const categoryList = [
    { 
      id: 1,
      value: 'tshirt', 
      label: 'T-Shirt',
    }, 
    { 
      id: 2, 
      value: 'hoodie', 
      label: 'Hoodie', 
    }, 
    {
      id: 3, 
      value: 'pants', 
      label: 'Pants',
    },
];

export const ratingList = [
  {
    id: 1,
    value: '1',
    label: '1🌟',
  },
  {
    id: 2,
    value: '2',
    label: '2🌟',
  },
  {
    id: 3,
    value: '3',
    label: '3🌟',
  },
  {
    id: 4,
    value: '4',
    label: '4🌟',
  },
  {
    id: 5,
    value: '5',
    label: '5🌟',
  },
];

export const dataList = [
  {
    id: 1,
    title: 'JUICE WRLD X VLONE 999 T-SHIRT BLACK',
    deliveryFee: 3.44,
    category: 'tshirt',
    cuisine: 'vlone',
    rating: 5,
    price: 2500,
    coverSrc: '/images/places/tricko1.jpg',
  },
  {
    id: 2,
    title: 'Juice wrld x Vlone hoodie',
    deliveryFee: 4.94,
    category: 'hoodie',
    cuisine: 'vlone',
    rating: 4,
    price: 1000,
    coverSrc: '/images/places/mikina1.jpg',
  },
  {
    id: 3,
    title: 'Palace M-Zone Mutant Fist Hoodie Black',
    deliveryFee: 4.94,
    category: 'hoodie',
    cuisine: 'palace',
    rating: 3,
    price: 2000,
    coverSrc: '/images/places/mikina2.jpg',
  },
  {
    id: 4,
    title: 'Nike Sportswear Club Fleece Cargo Trousers',
    deliveryFee: 2.14,
    category: 'pants',
    cuisine: 'nike',
    rating: 1,
    price: 1800,
    coverSrc: '/images/places/nohavice1.jpg',
  },
  {
    id: 5,
    title: 'Supreme Scratch Tee',
    deliveryFee: 6.79,
    category: 'tshirt',
    cuisine: 'supreme',
    rating: 5,
    price: 2000,
    coverSrc: '/images/places/tricko2.jpg',
  },
  {
    id: 6,
    title: 'stories noodles',
    serviceTime: '5-15min',
    deliveryFee: 2.87,
    category: 'hoodie',
    cuisine: 'nike',
    rating: 5,
    price: 3500,
    coverSrc: '/images/places/mikina3.jpg',
  },
  {
    id: 7,
    title: 'ASSC T-SHIRT "ZEN OUT"',
    deliveryFee: 8.5,
    category: 'tshirt',
    cuisine: 'assc',
    rating: 2,
    price: 2200,
    coverSrc: '/images/places/tricko3.jpg',
  },
  {
    id: 8,
    title: 'Palace Nature Pants Blanch Cargo',
    deliveryFee: 1.8,
    category: 'pants',
    cuisine: 'palace',
    rating: 1,
    price: 1900,
    coverSrc: '/images/places/nohavice2.jpg',
  },
  {
    id: 9,
    title: 'Palace T-Shirts',
    deliveryFee: 3.33,
    category: 'tshirts',
    cuisine: 'palace',
    rating: 4,
    price: 2750,
    coverSrc: '/images/places/tricko4.jpg',
  },
  {
    id: 10,
    title: 'Supreme Grey Box Logo Hoodie',
    deliveryFee: 1.9,
    category: 'hoodie',
    cuisine: 'supreme',
    rating: 2,
    price: 4350,
    coverSrc: '/images/places/mikina4.jpg',
  },
  {
    id: 11,
    title: 'Assc',
    deliveryFee: 4.1,
    category: 'tshirt',
    cuisine: 'assc',
    rating: 3,
    price: 3300,
    coverSrc: '/images/places/tricko5.jpg',
  },
  {
    id: 12,
    title: 'Juice Wrld x Vlone Butterfly T-shirt',
    deliveryFee: 1.5,
    category: 'tshirt',
    cuisine: 'vlone',
    rating: 2,
    price: 4100,
    coverSrc: '/images/places/tricko6.jpg',
  },
];
