export const categoryList = [
    {
      id: 1,
      value: 'nike',
      label: 'Nike',
    },
    {
      id: 2,
      value: 'adidas',
      label: 'Adidas',
    },
    {
      id: 3,
      value: 'puma',
      label: 'Puma',
    },
    {
      id: 3,
      value: 'vans',
      label: 'Vans',
    },
    {
      id: 3,
      value: 'newbalance',
      label: 'New Balance',
    },
  ];
  
  export const ratingList = [
    {
      id: 1,
      value: '1',
      label: '1🌟',
    },
    {
      id: 2,
      value: '2',
      label: '2🌟',
    },
    {
      id: 3,
      value: '3',
      label: '3🌟',
    },
    {
      id: 4,
      value: '4',
      label: '4🌟',
    },
    {
      id: 5,
      value: '5',
      label: '5🌟',
    },
  ];
  
  export const dataList = [
    {
      id: 1,
      title: 'Air Jordan 1 High OG Bred',
      deliveryFee: 3.44,
      category: 'nike',
      cuisine: 'air jordan',
      rating: 5,
      price: 500,
      coverSrc: '/images/places/airjordan2.jpg',
    },
    {
      id: 2,
      title: 'Air Jordan 1 Retro High OG',
      deliveryFee: 4.94,
      category: 'nike',
      cuisine: 'air jordan',
      rating: 4,
      price: 370,
      coverSrc: '/images/places/airjordan3.jpg',
    },
    {
      id: 3,
      title: 'Air Jordan 4 Retro University Blue',
      deliveryFee: 4.94,
      category: 'nike',
      cuisine: 'air jordan',
      rating: 3,
      price: 2000,
      coverSrc: '/images/places/tenisky.jpg',
    },
    {
      id: 4,
      title: 'Nike Run Swift 2',
      deliveryFee: 2.14,
      category: 'nike',
      cuisine: 'running',
      rating: 1,
      price: 40,
      coverSrc: '/images/places/nike6.jpg',
    },
    {
      id: 5,
      title: 'Nike ZoomX Streakfly',
      deliveryFee: 6.79,
      category: 'nike',
      cuisine: 'running',
      rating: 5,
      price: 120,
      coverSrc: 'images/places/nike5.jpg',
    },
    {
      id: 6,
      title: 'Nike Offcourt',
      deliveryFee: 2.87,
      category: 'nike',
      cuisine: 'slides',
      rating: 5,
      price: 3500,
      coverSrc: '/images/dishes/slides3.jpg',
    },
    {
      id: 7,
      title: 'Swift Run Shoes',
      deliveryFee: 8.5,
      category: 'adidas',
      cuisine: 'running',
      rating: 2,
      price: 2200,
      coverSrc: '/images/dishes/adidas.jpg',
    },
    {
      id: 8,
      title: 'Adidas 4D Run 1.0 Sshoes',
      deliveryFee: 1.8,
      category: 'adidas',
      cuisine: 'running',
      rating: 1,
      price: 1900,
      coverSrc: '/images/dishes/adidas2.jpg',
    },
    {
      id: 9,
      title: 'Adidas UltraBOOST 4.0 DNA',
      deliveryFee: 3.33,
      category: 'adidas',
      cuisine: 'running',
      rating: 4,
      price: 140,
      coverSrc: '/images/dishes/adidas3.jpg',
    },
    {
      id: 10,
      title: 'Adidas Adilette Slide',
      deliveryFee: 1.9,
      category: 'adidas',
      cuisine: 'slides',
      rating: 2,
      price: 4350,
      coverSrc: '/images/dishes/slides1.jpg',
    },
    {
      id: 11,
      title: 'Adidas Yeezy Slides "Pure"',
      deliveryFee: 4.1,
      category: 'adidas',
      cuisine: 'slides',
      rating: 3,
      price: 3300,
      coverSrc: '/images/dishes/slides2.jpg',
    },
    {
      id: 12,
      title: 'Reebok Nano X2 Shoes',
      deliveryFee: 1.5,
      category: 'reebok',
      cuisine: 'running',
      rating: 2,
      price: 4100,
      coverSrc: '/images/dishes/reebok.jpg',
    },
  ];
  